language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ckgh96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ckgh96/docker-react npm run test

